name: Automated tests

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main
jobs:
  verify:
    name: Run Verify
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: 'maven'
      - name: Build with Maven
        run: mvn test -s github-maven-settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}



