name: Maven Release
on:
  workflow_dispatch:

jobs:
  maven-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Perform Maven Release
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          mvn --batch-mode -s github-maven-settings.xml release:prepare release:perform
        env:
          GITHUB_PAT: ${{ secrets.NOTIFY_REPOS_PAT }}

