name: Notify other repos
run-name: Notify repos on release of ${{ github.event.release.tag_name }}
on:
  release:
    types:
      - released
permissions:
  contents: read

jobs:
  echo-release-tag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release tag is '${{ github.event.release.tag_name }}'"
  notify-dependants:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ 'genopace/test-maven-release-dependant-1', 'genopace/test-maven-release-dependant-2' ]
    steps:
      - name: Get version from tag
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          RELEASE_VERSION=${TAG_NAME#genopace-test-artefact-}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
      - name: Notify dependant repos of new API release
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.NOTIFY_REPOS_PAT }}
          repository: ${{ matrix.repo }}
          event-type: api-update
          client-payload: |-
            {
              "api_version": "${{ env.RELEASE_VERSION }}"
            }


