name: On Tag
on:
  create:

permissions:
  contents: read

jobs:
  on-tag:
    if: ${{ startsWith(github.ref, 'refs/tags/genopace-test-artefact-') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Found good tag ${{ github.event.create.git.ref }}!"


